traits = {
    ('rogue', 'assassination'): (
        'kingsbane',
        'assassins_blades',
        'toxic_blades',
        'poison_knives',
        'urge_to_kill',
        'balanced_blades',
        'surge_of_toxins',
        'shadow_walker',
        'master_assassin',
        'shadow_swiftness',
        'serrated_edge',
        'bag_of_tricks',
        'master_alchemist',
        'gushing_wounds',
        'fade_into_shadows',
        'from_the_shadows',
        'blood_of_the_assassinated',
        'slayers_precision',
    ),
    ('rogue', 'outlaw'): (
        'curse_of_the_dreadblades',
        'cursed_edges',
        'fates_thirst',
        'blade_dancer',
        'fatebringer',
        'gunslinger',
        'hidden_blade',
        'fortune_strikes',
        'ghostly_shell',
        'deception',
        'black_powder',
        'greed',
        'blurred_time',
        'fortunes_boon',
        'fortunes_strike',
        'blademaster',
        'blunderbuss',
        'cursed_steel',
        ),
    ('rogue', 'subtlety'): (
        'goremaws_bite',
        'shadow_fangs',
        'gutripper',
        'fortunes_bite',
        'catlike_reflexes',
        'embrace_of_darkness',
        'ghost_armor',
        'precision_strike',
        'energetic_stabbing',
        'flickering_shadows',
        'second_shuriken',
        'demons_kiss',
        'finality',
        'the_quiet_knife',
        'akarris_soul',
        'soul_shadows',
        'shadow_nova',
        'legionblade'
        ),
}

#Single Rank Traits for each spec
#Used for binary trait ranking
single_rank = {
    ('rogue', 'assassination'): (
        'kingsbane',
        'assassins_blades',
        'urge_to_kill',
        'surge_of_toxins',
        'shadow_swiftness',
        'bag_of_tricks',
        'from_the_shadows',
        'blood_of_the_assassinated',
    ),
    ('rogue', 'outlaw'): (
        'curse_of_the_dreadblades',
        'cursed_edges',
        'hidden_blade',
        'deception',
        'greed',
        'blurred_time',
        'blademaster',
        'blunderbuss',
        ),
    ('rogue', 'subtlety'): (
        'goremaws_bite',
        'shadow_fangs',
        'embrace_of_darkness',
        'flickering_shadows',
        'second_shuriken',
        'finality',
        'akarris_soul',
        'shadow_nova',
        ),
}